# Generated by Django 4.0.3 on 2022-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=250)),
                ('level1', models.IntegerField(default=0)),
                ('level2', models.IntegerField(default=0)),
                ('level3', models.IntegerField(default=0)),
                ('api_key', models.TextField(max_length=250)),
            ],
        ),
    ]
